//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmartResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmartResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smart.resources.SmartResources", typeof(SmartResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not found.
        /// </summary>
        public static string Api_Ex_element_not_found {
            get {
                return ResourceManager.GetString("Api_Ex_element_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element-handler not found.
        /// </summary>
        public static string Api_Ex_handler_not_found {
            get {
                return ResourceManager.GetString("Api_Ex_handler_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login..
        /// </summary>
        public static string Api_Ex_invalid_login {
            get {
                return ResourceManager.GetString("Api_Ex_invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match the rules..
        /// </summary>
        public static string Api_Ex_invalid_password {
            get {
                return ResourceManager.GetString("Api_Ex_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh-token is invalid..
        /// </summary>
        public static string Api_Ex_invalid_token {
            get {
                return ResourceManager.GetString("Api_Ex_invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh-token not found..
        /// </summary>
        public static string Api_Ex_refresh_token_not_found {
            get {
                return ResourceManager.GetString("Api_Ex_refresh_token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password is different from the new password..
        /// </summary>
        public static string Api_Ex_repeated_password_different {
            get {
                return ResourceManager.GetString("Api_Ex_repeated_password_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string Api_Ex_user_not_found {
            get {
                return ResourceManager.GetString("Api_Ex_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database connection.
        /// </summary>
        public static string Api_Init_missing_database {
            get {
                return ResourceManager.GetString("Api_Init_missing_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing host settings.
        /// </summary>
        public static string Api_Init_missing_urls {
            get {
                return ResourceManager.GetString("Api_Init_missing_urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh-token invalidated.
        /// </summary>
        public static string Api_Msg_token_revoked {
            get {
                return ResourceManager.GetString("Api_Msg_token_revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler.
        /// </summary>
        public static string Handler {
            get {
                return ResourceManager.GetString("Handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown client in HandlerHub.
        /// </summary>
        public static string Log_anonymous_connection {
            get {
                return ResourceManager.GetString("Log_anonymous_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create element.
        /// </summary>
        public static string Log_create_element {
            get {
                return ResourceManager.GetString("Log_create_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create element handler.
        /// </summary>
        public static string Log_create_handler {
            get {
                return ResourceManager.GetString("Log_create_handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element command.
        /// </summary>
        public static string Log_element_command {
            get {
                return ResourceManager.GetString("Log_element_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element state changed.
        /// </summary>
        public static string Log_element_state_changed {
            get {
                return ResourceManager.GetString("Log_element_state_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler offline.
        /// </summary>
        public static string Log_handler_offline {
            get {
                return ResourceManager.GetString("Log_handler_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler online.
        /// </summary>
        public static string Log_handler_online {
            get {
                return ResourceManager.GetString("Log_handler_online", resourceCulture);
            }
        }
    }
}
